#http://docs.travis-ci.com/user/languages/android/

language: android
jdk: oraclejdk7
env:
  matrix:
    - env: LOGGED_IN_TO_PARSE_PLATFORM=YES
    - env: LOGGED_IN_TO_PARSE_PLATFORM=NO
    #- ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

# I want faster builds of course, http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false
    
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-21.1.2

    # The SDK version used to compile your project
    #- android-21
    - Google Inc.:Google APIs:21 
    
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-17

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-19
    #- sys-img-x86-android-19



before_install:
  # for gradle output style
  - export TERM=dumb
  # environment info
  # - sudo chmod +x gradlew
  - gradle -v
  - uname -a
  - echo "Android Home:$ANDROID_HOME"
  # manually set sdk.dir variable, according to local paths
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
  - echo "Local Properties file is "
  - cat local.properties
  

  
before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

install: 
    - gradle clean 
    - gradle build

script: 
    - gradle check

    
    
    
    
    
    
    
